on: push
name: Deploy Pipeline PowerBI

env:
  IMAGE_NAME: oder2701/mia-pbi
  K3S_DEPLOYMENT: powerbi
  NAMESPACE: development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo GitHub/MIA-PowerBI
      uses: actions/checkout@v3

    - name: Login to DHR
      uses: docker/login-action@v2
      with:
        username: oder2701
        password: Concol1986*-16

    - name: Build and Push
      run: |
        docker build -t docker.io/${{ env.IMAGE_NAME }}:latest .
        docker push docker.io/${{ env.IMAGE_NAME }}:latest
        
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
       version: 'latest'  
       
    - name: Set KUBECONFIG from secret
      run: |
         export KUBECONFIG=$HOME/.kube/config
 
         
    - name: Test kubectl connection
      run: kubectl get nodes
      
    - name: Deploy to K3S
      run: kubectl apply -f -n ${{ env.NAMESPACE }} .github/k3s/powerbi.yaml



  
