on: push
name: Deploy Pipeline PowerBI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo GitHub/MIA-PowerBI
      uses: actions/checkout@v3

    - name: Login to DHR
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}

    - name: Build and Push
      run: |
        docker build -t docker.io/${{ secrets.IMAGE_NAME }}:latest .
        docker push docker.io/${{ secrets.IMAGE_NAME }}:latest

    - name: Deploy tu K3s
      uses: steebchen/kubectl@master
      env:
        KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
      with: 
        args: apply -f .github/k3s/powerbi.yaml



  
