on: push
name: Deploy Pipeline CI/CD

env:
  IMAGE_NAME: oder2701/mia-pbi
  K3S_DEPLOYMENT: powerbi
  NAMESPACE: development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: oder2701
        password: Concol1986*-16

    - name: Build and push image
      run: |
        docker build -t docker.io/${{ env.IMAGE_NAME }}:latest .
        docker push docker.io/${{ env.IMAGE_NAME }}:latest

    - name: SSH into K3s server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.1.11
        username: root
        key: ${{ secrets.K3S_SSH_KEY }}
        script: |
          kubectl apply -f powerbi.yaml



  
