on: push
name: Deploy Pipeline CI/CD

env:
  IMAGE_NAME: oder2701/mia-pbi
  K3S_DEPLOYMENT: powerbi
  NAMESPACE: development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: oder2701
        password: Concol1986*-16

    - name: Build and push image
      run: |
        docker build -t docker.io/${{ env.IMAGE_NAME }}:latest .
        docker push docker.io/${{ env.IMAGE_NAME }}:latest

    - name: SSH into K3s server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.1.11
        username: root
        key: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAlblG7uAW7xkhM+EZgNOhLS6Qoy8BZqSBXNavTMv6+NwsdaU8uofq
5eoiTkwe3D0uUTMbbGexRXTvaPui8N3YvszU+GvQ6M46NJjdwmk4jrxdO+0NcPwtSkOzbs
I+iQMXbrszBXoh2u4cG2/dpOHLM2Vj558iWfVZ/cav68mwRYd1SH//g1iSgBuw4n1fdnoM
resPezFQywZxnpRQC8RFvogBpJwxybPIi7O+phyRp0wPtliaeSlS8j4bMC7e8wrTMepyoQ
nS4C5tvwUzNiAUo0MFX64S+9s1B4X57svp9W/6HQqSZvW9hhN/ujT9dYnFvQozyPi2ttsf
ey1CKnCvaG5GuSLIAUVf7PHmZ15Br2VZtrfz79eZ0aKMGBe+GIrNYGsUK5iyNc1WdUAjCA
ykmBDjdlpo8yRK0Z2xpPrcIhN1vit9MShHH7CFl3UJnE5WuCv04kGbW8Ye8qdqDm+8lnLM
K//n7IxDLBwHTrXQKBGga9GCK5oHtXZ94120lFxdnWmlhiM9LnMwhFvo6budzsNXfsh+/r
Ebmuyp+VpcwzsNeX+tzMUxIWjMSdn9uB1Ulctvua9voxNVxTX1wBPk7NvV5NVRMfmLQi+9
ZwbY0Wkr2Ss+eEwF4mcDDzL88NueTu77m+ueh3pIVrax/tNr1keahGkdwrl/lgiyluvr7S
EAAAdI6UEqD+lBKg8AAAAHc3NoLXJzYQAAAgEAlblG7uAW7xkhM+EZgNOhLS6Qoy8BZqSB
XNavTMv6+NwsdaU8uofq5eoiTkwe3D0uUTMbbGexRXTvaPui8N3YvszU+GvQ6M46NJjdwm
k4jrxdO+0NcPwtSkOzbsI+iQMXbrszBXoh2u4cG2/dpOHLM2Vj558iWfVZ/cav68mwRYd1
SH//g1iSgBuw4n1fdnoMresPezFQywZxnpRQC8RFvogBpJwxybPIi7O+phyRp0wPtliaeS
lS8j4bMC7e8wrTMepyoQnS4C5tvwUzNiAUo0MFX64S+9s1B4X57svp9W/6HQqSZvW9hhN/
ujT9dYnFvQozyPi2ttsfey1CKnCvaG5GuSLIAUVf7PHmZ15Br2VZtrfz79eZ0aKMGBe+GI
rNYGsUK5iyNc1WdUAjCAykmBDjdlpo8yRK0Z2xpPrcIhN1vit9MShHH7CFl3UJnE5WuCv0
4kGbW8Ye8qdqDm+8lnLMK//n7IxDLBwHTrXQKBGga9GCK5oHtXZ94120lFxdnWmlhiM9Ln
MwhFvo6budzsNXfsh+/rEbmuyp+VpcwzsNeX+tzMUxIWjMSdn9uB1Ulctvua9voxNVxTX1
wBPk7NvV5NVRMfmLQi+9ZwbY0Wkr2Ss+eEwF4mcDDzL88NueTu77m+ueh3pIVrax/tNr1k
eahGkdwrl/lgiyluvr7SEAAAADAQABAAACAApNAKXAT+8LzrL7Un4lETqL+eAN8mlMjBZz
6QQr3sOTMkhtxiJk5cUnpt5IKUPxvjCZq9IwDvni6xbjX/kHfJSPW6jF/+AJCVVDVNeZQ+
oCn5igJjqW44EUNZqo36dmEsQQ8QX4TNNpITVXvusnGkL1iMyh1LnDHYvgbYu8LWgo56B8
cDHXvLo/my3Qx3xLf52Is2DSqlSbNb6Caa5FkAyJucM2U8xJlebbNF3IvWSdc1GSSvnUuJ
Gd+6u7iThaRgTftKzwOF67gLe2PeAERrl/C8h1Hb+Gsry46Yle5GTmtnYuLXKmPhQSgskd
rwpr+9cDqqz6+vlmwoW1hyFCpJM8EqmwVuiwDEivZ6nlLvtFRMQEDM7CbZCzB5IC3JShVc
hu/+i+rr0FGnD07IOTT+tTTFdhqJWobVgKTHv+c+TdenqOOAB/lhM/0s870G7mOY0drZMp
SbBoooATfF0EfepjXjZEVe4vZQyIbyYtm7hzSjKUs6Cn4OfKLc/bnwe31z3iyJA9eE7FP9
J1n07AzDImeFW5m07iHjESZMtN8YbtRoyxQa2geOzAU949ycChUGvrByl1L/rbmHF1mc5M
tD3WecykUMmGgUVOdNvkKyFl8TN3asnWKPOY7xKF80bX2nMd5wBK5xC/CjoPhQrGMlU3iB
skkda4EvVCWclz1OUZAAABAGJUU326nkFSFDxVFZSiXRDtiDyFkkXN8NdwN1Bolw24Gc7Z
WwjQOZxwvMf3JgIC5A9j6N8bYZlhEqXEQMVtrketIkBLokGKK+sol4OyuPS9MilwuUQ8m8
fNFukysmSzLhvoUdwKa1Yzz42c1rfFR+0LDCpMl3CVtXMTQJiwxLuqf59CVP9mdmlW+Q8z
mtgUs7vnq+1Nk1HQLQEsErQ5O+ZtLprnYHY0p/D6+kdI2WFBUv9/NH+9ULTn1500TuDw33
czX0NQK75ke7IU2m08GrqYK2EHF/hRZvU3BX02+e7kNBlAFkU4diWho+smi8qbixILDMkB
ggrHat5EUfj3YoMAAAEBAMjb9W5QzF/t5PoI332ITUkyuMbJvoUECtFHKEgNqENc5FQkDz
H2PpvAGnOrHp1f4gk04OmjBHv4BblyDVLP206GRlXY6WRqJ/ENbOXT0c3XLQEAWoTHsS6o
7qHh112rCPdJLPCInegf7v26Qx9Hbnn4QjS9at/3sM8AHPIrC7noBL2nVUZ859UDlanEaa
N6WjpSdiRgW+0q35K2rxq5Xf+gehGJxrRZfg10lHJC9jz1exVmJBcOZHYP7CJZzEC+w3Cj
cXBizPs54264f2VizFkhotw23iVRkRjDMbJK5NYS3IzzwxN6SQvuWZ4gxI2VnJLoPwovKz
SzyoonRSkx5N8AAAEBAL7TmtVYonhxa/ZaZitDaDH8MK/bVwy/OY37LlKduyHgzZO/P5ob
ONpw0D/3iOQUXZl0tq3yyuU2dmOosdFrpu/MgfdV75KxrCBkit3fnIo9AXyHcCJcZyeKzf
Aor/k6cnb776aEnunnSUP8kL6CzPPsan+GTVGeF+nDxWXXb+EFnWxo0zoPxDOcmvDKAjzc
J3mlZM1D1mqgK6ffVnyeTQxUmgVj42xV9F0LD0MqV1nEJXcRKjfLF0BYEf9K0MGZOfT5qK
kxi+r36pItPtjRRvHAc6AXzTqteC4fzxJpyAkrgNU/xQKdaPWSZSRtiea+yRFUiMBScktK
grqi2j36bf8AAAARcm9vdEBrM3MtbWFzdGVyMDEBAg==
        script: |
          kubectl apply -f powerbi.yaml



  
