on: push
name: Deploy Pipeline PowerBI

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout Repo GitHub/MIA-PowerBI
      uses: actions/checkout@v3

    - name: Login to DHR
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}

    - name: Build and Push
      run: |
        docker build -t docker.io/${{ secrets.IMAGE_NAME }}:latest .
        docker push docker.io/${{ secrets.IMAGE_NAME }}:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
         version: 'latest'

    - name: Set KUBECONFIG from secret
      run: |
       echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config
       chmod 600 $HOME/.kube/config

    - name: Test kubectl connection
      run: kubectl get nodes

    - name: Deploy
      run: kubectl apply -f -n ${{ secrets.NAMESPACE }} ${{ secrets.REPO }}



  
