on: push
name: Deploy Pipeline PowerBI

env:
  IMAGE_NAME: oder2701/mia-pbi
  K3S_DEPLOYMENT: powerbi
  NAMESPACE: development

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]
    
    steps:
    - name: Checkout Repo GitHub/MIA-PowerBI
      uses: actions/checkout@v3

    - name: Login to DHR
      uses: docker/login-action@v2
      with:
        username: oder2701
        password: Concol1986*-16

    - name: Build and Push
      run: |
        docker build -t docker.io/${{ env.IMAGE_NAME }}:latest .
        docker push docker.io/${{ env.IMAGE_NAME }}:latest

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.1.11
        username: root
        password: Root123
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl apply -f -n ${{ env.NAMESPACE }} .github/k3s/powerbi.yaml



  
