on: push
name: Deploy Pipeline CI/CD

env:
  IMAGE_NAME: oder2701/mia-pbi
  K3S_DEPLOYMENT: powerbi
  NAMESPACE: development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: oder2701
        password: Concol1986*-16

    - name: Build and push image
      run: |
        docker build -t docker.io/${{ env.IMAGE_NAME }}:latest .
        docker push docker.io/${{ env.IMAGE_NAME }}:latest

    - name: SSH into K3s server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.1.11
        username: root
        key: AAAAB3NzaC1yc2EAAAADAQABAAACAQCVuUbu4BbvGSEz4RmA06EtLpCjLwFmpIFc1q9My/r43Cx1pTy6h+rl6iJOTB7cPS5RMxtsZ7FFdO9o+6Lw3di+zNT4a9Dozjo0mN3CaTiOvF077Q1w/C1KQ7Nuwj6JAxduuzMFeiHa7hwbb92k4cszZWPnnyJZ9Vn9xq/rybBFh3VIf/+DWJKAG7DifV92egyt6w97MVDLBnGelFALxEW+iAGknDHJs8iLs76mHJGnTA+2WJp5KVLyPhswLt7zCtMx6nKhCdLgLm2/BTM2IBSjQwVfrhL72zUHhfnuy+n1b/odCpJm9b2GE3+6NP11icW9CjPI+La22x97LUIqcK9obka5IsgBRV/s8eZnXkGvZVm2t/Pv15nRoowYF74Yis1gaxQrmLI1zVZ1QCMIDKSYEON2WmjzJErRnbGk+twiE3W+K30xKEcfsIWXdQmcTla4K/TiQZtbxh7yp2oOb7yWcswr/+fsjEMsHAdOtdAoEaBr0YIrmge1dn3jXbSUXF2daaWGIz0uczCEW+jpu53Ow1d+yH7+sRua7Kn5WlzDOw15f63MxTEhaMxJ2f24HVSVy2+5r2+jE1XFNfXAE+Ts29Xk1VEx+YtCL71nBtjRaSvZKz54TAXiZwMPMvzw255O7vub656HekhWtrH+02vWR5qEaR3CuX+WCLKW6+vtIQ== root@k3s-master01
        script: |
          kubectl apply -f powerbi.yaml



  
