on: push
name: Deploy Pipeline PowerBI

jobs:
  build-and-deploy:
    runs-on: [self-hosted]

    steps:
    - name: Checkout Repo PowerBI
      uses: actions/checkout@v3

    - name: Login to DHR
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}

    - name: Build and Push Image PowerBI
      run: |
        docker build -t docker.io/${{ secrets.IMAGE_NAME }}:latest .
        docker push docker.io/${{ secrets.IMAGE_NAME }}:latest
          
    - name: Deploy PowerBI to K3s
      run: |
        kubectl replace -f ${{ secrets.REPO }}



  
